name: Pipeline

on:
  push:
    branches:
      - master
      - ci # branch for testing

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'

      # Run the scrappers
      - working-directory: ./go
        run: |
          go test ./...
          ./hack/run.sh

      - run: |
          cat data/articles.json

      # Build the nextjs application using
      # the data from the scrappers
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          # TODO put this into a script
          npm install
          npm test
          npm run build

          # TODO
          # publish the /out directory
        working-directory: ./espanelm

      # deploy to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./espanelm/out

      # publish the scrapped data back to the git repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: push scrapped pages
          file_pattern: data/**/*
