name: espanelm-news-digest
on:
  schedule:
  - cron: 0 */12 * * *
  push:
    branches:
      - master

jobs:
  build:
    name: espanelm-news-digest
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
